pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
  kartotherian:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: production-kartotherian
        build: production-kartotherian
        publish:
          image:
            tags: [kartotherian]

